name: Automated Code Review

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history
        ref: ${{ github.head_ref }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Ollama
      run: |
        curl -fsSL https://ollama.ai/install.sh | sh
        sudo systemctl start ollama
        sleep 10
        ollama pull mistral
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
          **.py
    
    - name: Run code review
      id: code-review
      run: |
        python automated_code_reviewer.py > review_output.txt 2>&1
        
        # Extract score from output
        #SCORE=$(grep -o "Score: [0-9]\+/100" review_output.txt | grep -o "[0-9]\+" | tail -1)
        #SCORE=$(grep -oE "Score: [0-9]+/100" review_output.txt | grep -oE "[0-9]+" | head -1)
        SCORE=$(grep -oE "\b[0-9]+/100\b" review_output.txt | cut -d'/' -f1 | head -1)
        if [ -z "$SCORE" ]; then
          SCORE=0
        fi
        
        # Set outputs
        echo "score=$SCORE" >> $GITHUB_OUTPUT
        echo "passed=$([ $SCORE -ge 80 ] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
        
        # Display results
        echo "Review Score: $SCORE/100"
        echo "Review Passed: $([ $SCORE -ge 80 ] && echo 'YES' || echo 'NO')"
        
        # Show full output
        echo "Full Review Output:"
        cat review_output.txt
